# Generated by Django 3.0.4 on 2020-04-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAllocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_one_score', models.IntegerField()),
                ('one_two_score', models.IntegerField()),
                ('one_three_score', models.IntegerField()),
                ('two_one_score', models.IntegerField()),
                ('two_two_score', models.IntegerField()),
                ('two_three_score', models.IntegerField()),
            ],
        ),
    ]
