# Generated by Django 3.0.4 on 2020-04-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanallocationmodel',
            name='one_one_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='loanallocationmodel',
            name='one_three_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='loanallocationmodel',
            name='one_two_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='loanallocationmodel',
            name='two_one_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='loanallocationmodel',
            name='two_three_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='loanallocationmodel',
            name='two_two_score',
            field=models.IntegerField(default=-1),
        ),
    ]
