# Generated by Django 3.0.4 on 2020-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_auto_20200407_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='BailJudgementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_one_score', models.IntegerField(default=-1)),
                ('two_one_score', models.IntegerField(default=-1)),
                ('three_one_score', models.IntegerField(default=-1)),
                ('four_one_score', models.IntegerField(default=-1)),
                ('one_two_score', models.IntegerField(default=-1)),
                ('two_two_score', models.IntegerField(default=-1)),
                ('three_two_score', models.IntegerField(default=-1)),
                ('four_two_score', models.IntegerField(default=-1)),
            ],
        ),
    ]
